#
#        Thank you for downloading         
#            ChatWarn v:1.5.0
# WHATS NEW:
# Added multi-language support
# A link to check what language code to use: https://ctrlq.org/code/19899-google-translate-languages
# Do not forget to scroll down past all of the code on the web page
# PERMISSIONS:
# chatwarn.checkupall
# chatwarn.setwarn
# chatwarn.warn
# chatwarn.uuid
# chatwarn.credits
# chatwarn.help
# chatwarn.reload
# chatwarn.banuuid
# chatwarn.notify
# chatwarn.checkup
# chatwarn.bypass
# chatwarn.bypassall (NOTE: ONLY GIVE THIS PERMISSION TO YOURSELF AND/OR CO-OWNER IT ALLOWS PEOPLE WITH THIS PERMISSION TO WARN ANYBODY EVEN IF THEY HAVE THE chatwarn.bypass PERMISSION!)
# NOTE:
# For easy player lookup do /checkupall or go to https://sessionserver.mojang.com/session/minecraft/profile/ and type in the UUID of the player you want but remove all "-" otherwise the link will not work
# For the FirstMuteTime, the SecondMuteTime, and the ThirdMuteTime
# The first mute time is in minutes
# The second mute time is in hours
# The third mute time is in days
# ( KEEP THIS IN MIND FOR SETTING TIMES)
#       END OF HEADER
# The prefix for the messages
ChatWarnPrefix: "&8[&2Chat&3Warn&8]"
ChatWarnUpdater: false
ChatWarnMuteToggle: false
FirstMuteTime: 10
SecondMuteTime: 1
ThirdMuteTime: 1
language: en_us