name: ChatWarn
version: 2.0.0
main: com.gmail.artizangaming.ChatWarn
description: Warn Other Players For Chat Related Issues!

commands:
    chatwarn:
        usage: /<command> 
        description: Basic Hub Command
    warn:
        usage: /<command> <player> <reason>
        description: Warns the specified player
permissions:
    chatwarn.mute:
        description: Permission node for the /chatmute command
        default: op
    chatwarn.checkupall:
        description: Permission node for the /checkupall command
        default: op
    chatwarn.setwarn:
        description: Sets the warn level for a player
        default: op
    chatwarn.warn:
        description: Allows for the user to use /warn to warn other players for chat related issues.
        default: op
    chatwarn.uuid:
        default: op
        description: Allows for the user to reset a player's UUID back to 0 warnings.
    chatwarn.credits:
        default: true
        description: Shows Credits Of ChatWarn Plugin
    chatwarn.help:
        default: true
        description: Shows Help For Plugin
    chatwarn.reload:
        default: op
        description: Reloads Plugin Configuration
    chatwarn.banuuid:
        default: op
        description: Bans a players uuid
    chatwarn.notify:
        default: op
        description: Notifys for a Players Punishment
    chatwarn.checkup:
        default: op
        description: Checks A Players Warn Level
    chatwarn.bypass:
        default: op
        description: Bypasses warnings and cannot be UUID banned
    chatwarn.bypassall:
        default: op
        description: Bypasses the chatwarn.bypass permission and can warn anybody on the server